name: 'CI - Go Build'

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['windows', 'darwin', 'linux']
        arch: ['arm64', 'amd64']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: true

      - name: Go Build
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}

          mkdir bin
          go build -o bin/${{ matrix.os }}-${{ matrix.arch }} main.go

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          tag: ${{ github.ref }}
          file: bin/${{ matrix.os }}-${{ matrix.arch }}
          asset_name: build-notifier-action_$tag-${{ matrix.os }}-${{ matrix.arch }}

  notification:
    needs: [build]
    if: always()
    name: Send Build Notification
    runs-on: ubuntu-latest

    steps:
      - name: Action Testing
        uses: zchryr/build-notifier-action@v1.0.11
        with:
          body: ${{ toJSON(needs) }}
          url: ${{ secrets.WEBHOOK_URL }}
          response_code: 201
          repo: ${{ github.repository }}
          workflow: $WORKFLOW
        env:
          WORKFLOW: ${{ github.workflow }}
